CREATE TABLE USERS (
    USER_ID SERIAL PRIMARY KEY,
    USER_NAME VARCHAR(255) NOT NULL,
    AMOUNT_OF_POSTS INTEGER NOT NULL
);
CREATE TABLE POSTS (
    POST_ID SERIAL PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    POST_TEXT TEXT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);
