version: '1.0'

services:
  postgresql-container-posts:
    image: postgres:latest
    container_name: postgresql-container-posts
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: k8training
    ports:
      - "5434:5432"
    volumes:
      - ./postgresql/initPosts.sql:/docker-entrypoint-initdb.d/initPosts.sql

  postgresql-container-users:
    image: postgres:latest
    container_name: postgresql-container-users
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: k8training
    ports:
      - "5433:5432"
    volumes:
      - ./postgresql/initUsers.sql:/docker-entrypoint-initdb.d/initUsers.sql

  container-users:
    image: ooo4u/user-service-1.0.0
    container_name: container-users
    ports:
      - "8082:8080"
    depends_on:
      - postgresql-container-users
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://postgresql-container-users:5432/k8training
      - DB_USER=user
      - DB_PASSWORD=password

  container-posts:
    image: ooo4u/post-service-1.0.0
    container_name: container-posts
    ports:
      - "8081:8080"
    depends_on:
      - postgresql-container-posts
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://postgresql-container-posts:5432/k8training
      - DB_USER=user
      - DB_PASSWORD=password
      - USERS_URL=http://container-users:8080
