CREATE TABLE IF NOT EXISTS POSTS (
    POST_ID SERIAL PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    POST_TEXT TEXT NOT NULL,
    CREATED_AT DATE NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS POST_SEQUENCE START 1 INCREMENT 1;