CREATE TABLE IF NOT EXISTS USERS (
    USER_ID SERIAL PRIMARY KEY,
    USER_NAME VARCHAR(255) NOT NULL,
    AMOUNT_OF_POSTS INTEGER NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS USER_SEQUENCE START 1 INCREMENT 1;