apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-program
  name: posts-service
spec:
  selector:
    matchLabels:
      app: posts-service-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: posts-service-pod
    spec:
      containers:
        - name: posts-service
          image: ooo4u/post-service:1.0.1
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8080
            #If app fails 3 consecutive health checks, 20 seconds apart, reboot the container
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8080
            #Ping the app every 5 seconds to make sure it's healthy. If fail two subsequent pings, cordone it off
            successThreshold: 2
            failureThreshold: 2
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8080
            #Check it every 5 seconds (give up after 5 sec) for up to 100s before k8s gets into a crash loop.
            successThreshold: 1
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: POSTS_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: USERS_URL
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: USERS_URL
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  namespace: k8s-program
  name: posts-service
spec:
  type: NodePort
  selector:
    app: posts-service-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
