apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-program
  name: posts-service
spec:
  selector:
    matchLabels:
      app: posts-service-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: posts-service-pod
    spec:
      containers:
        - name: posts-service
          image: ooo4u/post-service:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: DB_URL
              value: jdbc:postgresql://posts-db:5432/postgres
            - name: DB_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: USERS_URL
              value: http://users-service:8080
          resources:
            limits:
              memory: 1Gi
              cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  namespace: k8s-program
  name: posts-service
spec:
  type: NodePort
  selector:
    app: posts-service-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
