apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-program
  name: posts-service
spec:
  selector:
    matchLabels:
      app: posts-service-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: posts-service-pod
    spec:
      containers:
        - name: posts-service
          image: ooo4u/post-service:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: POSTS_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: USERS_URL
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: USERS_URL

---
apiVersion: v1
kind: Service
metadata:
  namespace: k8s-program
  name: posts-service
spec:
  type: NodePort
  selector:
    app: posts-service-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
