apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: k8s-program
  name: posts-db
spec:
  selector:
    matchLabels:
      app: posts-db
  serviceName: posts-db
  replicas: 1
  template:
    metadata:
      labels:
        app: posts-db
    spec:
      containers:
        - name: posts-db
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: posts-storage
  volumeClaimTemplates:
    - metadata:
        name: posts-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: hostpath
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  namespace: k8s-program
  name: posts-db
  labels:
    app: posts-db
spec:
  type: ClusterIP
  selector:
    app: posts-db
  ports:
    - port: 5432
      targetPort: 5432
