apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: k8s-program
  name: users-db
spec:
  selector:
    matchLabels:
      app: users-db
  serviceName: users-db
  replicas: 1
  template:
    metadata:
      labels:
        app: users-db
    spec:
      containers:
        - name: users-db
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: k8s-config
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: users-storage
              mountPath: "/var/lib/postgresql/data"
            - name: users-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: users-init
          configMap:
            name: k8s-config
            items:
              - key: USERS_SCHEMA_SQL
                path: "users-schema.sql"
  volumeClaimTemplates:
    - metadata:
        name: users-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: hostpath
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  namespace: k8s-program
  name: users-db
  labels:
    app: users-db
spec:
  type: ClusterIP
  selector:
    app: users-db
  ports:
    - port: 5432
      targetPort: 5432
